version: '3.7'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=demo
      - MYSQL_USER=layer
      - MYSQL_PASSWORD=demo
      - MYSQL_DATABASE=demo
    ports:
      - 3306:3306
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  app:
    image: layer/demo:latest
    ports:
      - 9090:9090
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx1024m"
    networks:
      - backend
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    networks:
      - backend
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  # Not required in production
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - db

networks:
  backend: